spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.50.221:3306/ltzServer?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
cat:
  privatekey: 12312312312321
